config/routes.rb
Rails.application.routes.draw do
  resources :blog_posts
  devise_for :users
  resources :build_services
  resources :cables
  resources :keyboards
  root 'home#index'
  get '/blog', to: 'blog#index'
  get '/shop/checkout', to: 'shop#checkout'
  get '/gallery', to: 'gallery#index'
  get '/gallery/keyboards', to: 'gallery#keyboards'
  get '/gallery/cables', to: 'gallery#cables'
  
  # This line mounts Solidus's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Solidus relies on it being the default of "spree"
  # mount Spree::Core::Engine, at: '/shop'

  # mount SolidusPaypalCommercePlatform::Engine, at: '/solidus_paypal_commerce_platform'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get ':controller(/:action(/:id))'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
end

app/models/build_service.rb
class BuildService < ApplicationRecord
end

app/models/cable.rb
class Cable < ApplicationRecord
  has_one_attached :photo
end

app/models/keyboard.rb
class Keyboard < ApplicationRecord
  has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  def index; end
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :set_blog_post, only: %i[ show edit update destroy ]

  # GET /blog_posts or /blog_posts.json
  def index
    @blog_posts = BlogPost.all
  end

  # GET /blog_posts/1 or /blog_posts/1.json
  def show
  end

  # GET /blog_posts/new
  def new
    @blog_post = BlogPost.new
  end

  # GET /blog_posts/1/edit
  def edit
  end

  # POST /blog_posts or /blog_posts.json
  def create
    @blog_post = BlogPost.new(blog_post_params)

    respond_to do |format|
      if @blog_post.save
        format.html { redirect_to @blog_post, notice: "Blog post was successfully created." }
        format.json { render :show, status: :created, location: @blog_post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blog_posts/1 or /blog_posts/1.json
  def update
    respond_to do |format|
      if @blog_post.update(blog_post_params)
        format.html { redirect_to @blog_post, notice: "Blog post was successfully updated." }
        format.json { render :show, status: :ok, location: @blog_post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blog_posts/1 or /blog_posts/1.json
  def destroy
    @blog_post.destroy
    respond_to do |format|
      format.html { redirect_to blog_posts_url, notice: "Blog post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog_post
      @blog_post = BlogPost.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_post_params
      params.require(:blog_post).permit(:title, :content)
    end
end

app/controllers/cables_controller.rb
class CablesController < ApplicationController
  before_action :set_cable, only: %i[show edit update destroy]

  # GET /cables or /cables.json
  def index
    @cables = Cable.all
  end

  # GET /cables/1 or /cables/1.json
  def show
    @cable = Cable.find(params[:id])
  end

  # GET /cables/new
  def new
    @cable = Cable.new
  end

  # GET /cables/1/edit
  def edit; end

  # POST /cables or /cables.json
  def create
    @cable = Cable.new(cable_params)

    respond_to do |format|
      if @cable.save
        format.html { redirect_to @cable, notice: 'Cable was successfully created.' }
        format.json { render :show, status: :created, location: @cable }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cable.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cables/1 or /cables/1.json
  def update
    respond_to do |format|
      if @cable.update(cable_params)
        format.html { redirect_to @cable, notice: 'Cable was successfully updated.' }
        format.json { render :show, status: :ok, location: @cable }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cable.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cables/1 or /cables/1.json
  def destroy
    @cable.destroy
    respond_to do |format|
      format.html { redirect_to cables_url, notice: 'Cable was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_cable
    @cable = Cable.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def cable_params
    params.fetch(:cable, {}).permit(:build_date, :paracord, :techflex, :heatshrink, :connector, :photo, :id)
  end
end

app/controllers/gallery_controller.rb
class GalleryController < ApplicationController
  def index; end

  def cables; end

  def keyboards; end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/keyboards_controller.rb
class KeyboardsController < ApplicationController
  before_action :set_keyboard, only: %i[show edit update destroy]

  # GET /keyboards or /keyboards.json
  def index
    @keyboards = Keyboard.all
  end

  # GET /keyboards/1 or /keyboards/1.json
  def show
    @keyboard = Keyboard.find(params[:id])
  end

  # GET /keyboards/new
  def new
    @keyboard = Keyboard.new
  end

  # GET /keyboards/1/edit
  def edit; end

  # POST /keyboards or /keyboards.json
  def create
    @keyboard = Keyboard.new(keyboard_params)

    respond_to do |format|
      if @keyboard.save
        format.html { redirect_to @keyboard, notice: 'Keyboard was successfully created.' }
        format.json { render :show, status: :created, location: @keyboard }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @keyboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /keyboards/1 or /keyboards/1.json
  def update
    respond_to do |format|
      if @keyboard.update(keyboard_params)
        format.html { redirect_to @keyboard, notice: 'Keyboard was successfully updated.' }
        format.json { render :show, status: :ok, location: @keyboard }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @keyboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /keyboards/1 or /keyboards/1.json
  def destroy
    @keyboard.destroy
    respond_to do |format|
      format.html { redirect_to keyboards_url, notice: 'Keyboard was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_keyboard
    @keyboard = Keyboard.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def keyboard_params
    params.fetch(:keyboard, {}).permit(:name, :build_date, :switches, :keycaps, :photo, :id)
  end
end

app/controllers/shop_controller.rb
class ShopController < ApplicationController
  def index; end

  def checkout; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/helpers/build_service_helper.rb
module BuildServiceHelper
end

app/helpers/build_services_helper.rb
module BuildServicesHelper
end

app/helpers/cables_helper.rb
module CablesHelper
end

app/helpers/gallery_helper.rb
module GalleryHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/keyboards_helper.rb
module KeyboardsHelper
end

app/helpers/shop_helper.rb
module ShopHelper
end

app/views/blog_posts/_form.html.erb
<%= form_with(model: blog_post) do |form| %>
  <% if blog_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog_post.errors.count, "error") %> prohibited this blog_post from being saved:</h2>

      <ul>
        <% blog_post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blog_posts/edit.html.erb
<h1>Editing Blog Post</h1>

<%= render 'form', blog_post: @blog_post %>

<%= link_to 'Show', @blog_post %> |
<%= link_to 'Back', blog_posts_path %>

app/views/blog_posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blog Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blog_posts.each do |blog_post| %>
      <tr>
        <td><%= blog_post.title %></td>
        <td><%= blog_post.content %></td>
        <td><%= link_to 'Show', blog_post %></td>
        <td><%= link_to 'Edit', edit_blog_post_path(blog_post) %></td>
        <td><%= link_to 'Destroy', blog_post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog Post', new_blog_post_path %>

app/views/blog_posts/new.html.erb
<h1>New Blog Post</h1>

<%= render 'form', blog_post: @blog_post %>

<%= link_to 'Back', blog_posts_path %>

app/views/blog_posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog_post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @blog_post.content %>
</p>

<%= link_to 'Edit', edit_blog_post_path(@blog_post) %> |
<%= link_to 'Back', blog_posts_path %>

app/views/cables/_form.html.erb
<%= form_with(model: cable) do |form| %>
<div class="form-group">
  <%= form.label :build_date %>
  <%= form.datetime_field :build_date, :class => 'form-control' %>
</div>
<div class="form-group">
  <%= form.label :paracord %>
  <%= form.text_field :paracord, :class => 'form-control' %>
</div>
<div class="form-group">
  <%= form.label :techflex %>
  <%= form.text_field :techflex, :class => 'form-control' %>
</div>
<div class="form-group">
  <%= form.label :heatshrink %>
  <%= form.text_field :heatshrink, :class => 'form-control' %>
</div>
<div class="form-group">
  <%= form.label :connector %>
  <%= form.text_field :connector, :class => 'form-control' %>
</div>
<div class="form-group">
  <%= form.label :photo %>
  <%= form.file_field :photo, :class => 'form-control', multiple: true%>
</div>


<% if cable.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(cable.errors.count, "error") %> prohibited this cable from being saved:</h2>

  <ul>
    <% cable.errors.each do |error| %>
    <li><%= error.full_message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="actions">
  <%= form.submit %>
</div>
<% end %>

app/views/cables/edit.html.erb
<h1>Editing Cable</h1>

<%= render 'form', cable: @cable %>

<%= link_to 'Show', @cable %> |
<%= link_to 'Back', cables_path %>

app/views/cables/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Cables<h1>
        <div class="album py-5 bg-dark">
            <% @cables.each do |cable| %>
            <div class="container">
                <div class="col">
                    <div class="card shadow-sm">
                        <svg class="bd-placeholder-img card-img-top" width="100%" height="225"
                            xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail"
                            preserveAspectRatio="xMidYMid slice" focusable="false">
                            <title>Placeholder</title>


                            <rect width="100%" height="100%" fill="#55595c"></rect><text x="0%" y="50%" fill="#eceeef"
                                dy=".3em"><%= image_tag cable.photo %></text>
                        </svg>

                        <div class="card-body">
                            <div class="card-text">

                                <p>Paracord Color: <%= cable.paracord %></p>
                                <p>Connector Type: <%= cable.connector %></p>
                                <p>Build Date: <%= cable.build_date %></p>
                            </div>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <button type="button"
                                        class="btn btn-sm btn-outline-secondary"><%= link_to 'Show', cable %></button>
                                    <button type="button"
                                        class="btn btn-sm btn-outline-secondary"><%= link_to 'Edit', edit_cable_path(cable) %></button>
                                    <button type="button"
                                        class="btn btn-sm btn-outline-secondary"><%= link_to 'Destroy', cable, method: :delete, data: { confirm: 'Are you sure?' } %></button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <% end %>
        </div>

        

        <p><%= link_to 'New Cable', new_cable_path %></p>

app/views/cables/new.html.erb
<h1>New Cable</h1>

<%= render 'form', cable: @cable %>

<%= link_to 'Back', cables_path %>

app/views/cables/show.html.erb
<p id="notice"><%= notice %></p>

<%= @cable.photo %>
<p>Paracord Color: <%= @cable.paracord %></p>
<p>Techflex Color: <%= @cable.techflex %></p>
<p>Heatshrink Color: <%= @cable.heatshrink %></p>
<p>Connector Type: <%= @cable.connector %></p>
<p>Build Date: <%= @cable.build_date %></p>

<%= link_to 'Edit', edit_cable_path(@cable) %> |
<%= link_to 'Back', cables_path %>

app/views/keyboards/_form.html.erb
<%= form_with(model: keyboard) do |form| %>
    <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, :class => 'form-control' %>
    </div>
    <div class="form-group">
    <%= form.label :build_date %>
    <%= form.datetime_field :build_date, :class => 'form-control' %>
    </div>
    <div class="form-group">
    <%= form.label :switches %>
    <%= form.text_field :switches, :class => 'form-control' %>
    </div>
    <div class="form-group">
    <%= form.label :keycaps %>
    <%= form.text_field :keycaps, :class => 'form-control' %>
    </div>
     <div class="form-group">
    <%= form.label :photo %>
    <%= form.file_field :photo, :class => 'form-control' %>
    </div>
  
  <% if keyboard.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(keyboard.errors.count, "error") %> prohibited this keyboard from being saved:</h2>

      <ul>
        <% keyboard.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/keyboards/edit.html.erb
<h1>Editing Keyboard</h1>

<%= render 'form', keyboard: @keyboard %>

<%= link_to 'Show', @keyboard %> |
<%= link_to 'Back', keyboards_path %>

app/views/keyboards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Keyboards</h1>
<div class="album py-5 bg-dark">
            <% @keyboards.each do |keyboard| %>
            <div class="container">
                <div class="col">
                    <div class="card shadow-sm">
                        <svg class=" card-img-top" width="100%" height="225"
                            preserveAspectRatio="xMidYMid slice" focusable="false">
                            <title><%= keyboard.name %></title>
                            <%= image_tag keyboard.photo %>
                        </svg>

                        <div class="card-body">
                            <div class="card-text">
                                <p>Keyboard: <%= keyboard.name %></p>
                                <p>Switches: <%= keyboard.switches %></p>
                                <p>Keycaps: <%= keyboard.keycaps %></p>
                                <p>Build Date: <%= keyboard.build_date %></p>
                            </div>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <button type="button"
                                        class="btn btn-sm btn-outline-secondary"><%= link_to 'Show', keyboard %></button>
                                    <button type="button"
                                        class="btn btn-sm btn-outline-secondary"><%= link_to 'Edit', edit_keyboard_path(keyboard) %></button>
                                    <button type="button"
                                        class="btn btn-sm btn-outline-secondary"><%= link_to 'Destroy', keyboard, method: :delete, data: { confirm: 'Are you sure?' } %></button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <% end %>
        </div>

<%= link_to 'New Keyboard', new_keyboard_path %>

app/views/keyboards/new.html.erb
<h1>New Keyboard</h1>

<%= render 'form', keyboard: @keyboard %>

<%= link_to 'Back', keyboards_path %>

app/views/keyboards/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @keyboard.name %></h1>
<%= @keyboard.photo %>
<p>Switches: <%= @keyboard.switches %></p>
<p>Keycaps: <%= @keyboard.keycaps %></p>
<p>Build Date: <%= @keyboard.build_date %></p>

<%= link_to 'Edit', edit_keyboard_path(@keyboard) %> |
<%= link_to 'Back', keyboards_path %>