config/routes.rb
Rails.application.routes.draw do
  resources :blog_posts
  devise_for :users
  resources :build_services
  resources :cables
  resources :keyboards
  root 'home#index'
  get '/blog', to: 'blog#index'
  get '/shop/checkout', to: 'shop#checkout'
  get '/gallery', to: 'gallery#index'
  get '/gallery/keyboards', to: 'gallery#keyboards'
  get '/gallery/cables', to: 'gallery#cables'
  
  # This line mounts Solidus's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Solidus relies on it being the default of "spree"
  # mount Spree::Core::Engine, at: '/shop'

  # mount SolidusPaypalCommercePlatform::Engine, at: '/solidus_paypal_commerce_platform'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get ':controller(/:action(/:id))'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
end

app/models/build_service.rb
class BuildService < ApplicationRecord
end

app/models/cable.rb
class Cable < ApplicationRecord
  has_one_attached :photo
end

app/models/keyboard.rb
class Keyboard < ApplicationRecord
  has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  def index; end
end

app/controllers/cables_controller.rb
class CablesController < ApplicationController
  before_action :set_cable, only: %i[show edit update destroy]

  # GET /cables or /cables.json
  def index
    @cables = Cable.all
  end

  # GET /cables/1 or /cables/1.json
  def show
    @cable = Cable.find(params[:id])
  end

  # GET /cables/new
  def new
    @cable = Cable.new
  end

  # GET /cables/1/edit
  def edit; end

  # POST /cables or /cables.json
  def create
    @cable = Cable.new(cable_params)

    respond_to do |format|
      if @cable.save
        format.html { redirect_to @cable, notice: 'Cable was successfully created.' }
        format.json { render :show, status: :created, location: @cable }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cable.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cables/1 or /cables/1.json
  def update
    respond_to do |format|
      if @cable.update(cable_params)
        format.html { redirect_to @cable, notice: 'Cable was successfully updated.' }
        format.json { render :show, status: :ok, location: @cable }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cable.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cables/1 or /cables/1.json
  def destroy
    @cable.destroy
    respond_to do |format|
      format.html { redirect_to cables_url, notice: 'Cable was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_cable
    @cable = Cable.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def cable_params
    params.fetch(:cable, {}).permit(:build_date, :paracord, :techflex, :heatshrink, :connector, :photo, :id)
  end
end

app/controllers/gallery_controller.rb
class GalleryController < ApplicationController
  def index; end

  def cables; end

  def keyboards; end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/keyboards_controller.rb
class KeyboardsController < ApplicationController
  before_action :set_keyboard, only: %i[show edit update destroy]

  # GET /keyboards or /keyboards.json
  def index
    @keyboards = Keyboard.all
  end

  # GET /keyboards/1 or /keyboards/1.json
  def show
    @keyboard = Keyboard.find(params[:id])
  end

  # GET /keyboards/new
  def new
    @keyboard = Keyboard.new
  end

  # GET /keyboards/1/edit
  def edit; end

  # POST /keyboards or /keyboards.json
  def create
    @keyboard = Keyboard.new(keyboard_params)

    respond_to do |format|
      if @keyboard.save
        format.html { redirect_to @keyboard, notice: 'Keyboard was successfully created.' }
        format.json { render :show, status: :created, location: @keyboard }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @keyboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /keyboards/1 or /keyboards/1.json
  def update
    respond_to do |format|
      if @keyboard.update(keyboard_params)
        format.html { redirect_to @keyboard, notice: 'Keyboard was successfully updated.' }
        format.json { render :show, status: :ok, location: @keyboard }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @keyboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /keyboards/1 or /keyboards/1.json
  def destroy
    @keyboard.destroy
    respond_to do |format|
      format.html { redirect_to keyboards_url, notice: 'Keyboard was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_keyboard
    @keyboard = Keyboard.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def keyboard_params
    params.fetch(:keyboard, {}).permit(:name, :build_date, :switches, :keycaps, :photo, :id)
  end
end

app/controllers/shop_controller.rb
class ShopController < ApplicationController
  def index; end

  def checkout; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/helpers/build_service_helper.rb
module BuildServiceHelper
end

app/helpers/build_services_helper.rb
module BuildServicesHelper
end

app/helpers/cables_helper.rb
module CablesHelper
end

app/helpers/gallery_helper.rb
module GalleryHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/keyboards_helper.rb
module KeyboardsHelper
end

app/helpers/shop_helper.rb
module ShopHelper
end

app/views/blog/feed.html.erb
<h1>Blog</h1>

<h2></h2>
<h3>Example post</h3>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

<h3>Example post</h3>
<p>LLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quam elementum pulvinar etiam non. At tempor commodo ullamcorper a lacus. Diam in arcu cursus euismod. Vel fringilla est ullamcorper eget nulla. Nec tincidunt praesent semper feugiat nibh sed. Vitae tortor condimentum lacinia quis.</p>

app/views/blog/index.html.erb
<h1>Blog</h1>

<h2></h2>
<h3>Example post</h3>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

<h3>Example post</h3>
<p>LLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quam elementum pulvinar etiam non. At tempor commodo ullamcorper a lacus. Diam in arcu cursus euismod. Vel fringilla est ullamcorper eget nulla. Nec tincidunt praesent semper feugiat nibh sed. Vitae tortor condimentum lacinia quis.</p>

app/views/gallery/gallery.html.erb
<h1>Gallery</h1>

<h2><a href="keyboards">Keyboards</a></h2>

<h2><a href="cables">Cables</a></h2>

app/views/gallery/index.html.erb
<h1>Gallery</h1>

<h2><a href="gallery/keyboards">Keyboards</a></h2>
<div class="album py-5 bg-light">
  <div class="container">

    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
      <div class="col">
        <div class="card shadow-sm">
          <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg"
            role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false">
            <title>Placeholder</title>
            <rect width="100%" height="100%" fill="#55595c"></rect><text x="50%" y="50%" fill="#eceeef"
              dy=".3em">Thumbnail</text>
          </svg>

          <div class="card-body">
            <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional
              content. This content is a little bit longer.</p>
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
              </div>
              <small class="text-muted">9 mins</small>
            </div>
          </div>
        </div>
      </div>
      <div class="col">
        <div class="card shadow-sm">
          <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg"
            role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false">
            <title>Placeholder</title>
            <rect width="100%" height="100%" fill="#55595c"></rect><text x="50%" y="50%" fill="#eceeef"
              dy=".3em">Thumbnail</text>
          </svg>

          <div class="card-body">
            <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional
              content. This content is a little bit longer.</p>
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
              </div>
              <small class="text-muted">9 mins</small>
            </div>
          </div>
        </div>
      </div>
      <div class="col">
        <div class="card shadow-sm">
          <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg"
            role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false">
            <title>Placeholder</title>
            <rect width="100%" height="100%" fill="#55595c"></rect><text x="50%" y="50%" fill="#eceeef"
              dy=".3em">Thumbnail</text>
          </svg>

          <div class="card-body">
            <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional
              content. This content is a little bit longer.</p>
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
              </div>
              <small class="text-muted">9 mins</small>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
</div>
<h2><a href="gallery/cables">Cables</a></h2>
<div class="album py-5 bg-light">
  <div class="container">

    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
      <div class="col">
        <div class="card shadow-sm">
          <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg"
            role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false">
            <title>Placeholder</title>
            <rect width="100%" height="100%" fill="#55595c"></rect><text x="50%" y="50%" fill="#eceeef"
              dy=".3em">Thumbnail</text>
          </svg>

          <div class="card-body">
            <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional
              content. This content is a little bit longer.</p>
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
              </div>
              <small class="text-muted">9 mins</small>
            </div>
          </div>
        </div>
      </div>
      <div class="col">
        <div class="card shadow-sm">
          <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg"
            role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false">
            <title>Placeholder</title>
            <rect width="100%" height="100%" fill="#55595c"></rect><text x="50%" y="50%" fill="#eceeef"
              dy=".3em">Thumbnail</text>
          </svg>

          <div class="card-body">
            <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional
              content. This content is a little bit longer.</p>
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
              </div>
              <small class="text-muted">9 mins</small>
            </div>
          </div>
        </div>
      </div>
      <div class="col">
        <div class="card shadow-sm">
          <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg"
            role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false">
            <title>Placeholder</title>
            <rect width="100%" height="100%" fill="#55595c"></rect><text x="50%" y="50%" fill="#eceeef"
              dy=".3em">Thumbnail</text>
          </svg>

          <div class="card-body">
            <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional
              content. This content is a little bit longer.</p>
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
              </div>
              <small class="text-muted">9 mins</small>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
</div>

app/views/home/index.html.erb
    <%# <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  <header class="mb-auto">
    <div>
      <h3 class="float-md-start mb-0">Cover</h3>
      <nav class="nav nav-masthead justify-content-center float-md-end">
        <a class="nav-link active" aria-current="page" href="#">Home</a>
        <a class="nav-link" href="#">Features</a>
        <a class="nav-link" href="#">Contact</a>
      </nav>
    </div>
  </header> %>

    <main class="px-3">
      <div class="bio lead">
        <p class="lead">Hey there! I'm Dani, a keyboard enthusiast who makes custom keyboard cables. Follow along to see
          my custom keyboard journey.</p>
      </div>
        <div class="lead blog">
          <h2><%= link_to "My Keyboard Journey", blog_posts_path %></h2>
          <p>Want to know how I got into the hobby? Have questions about my recent builds? This is the place to be.</p>
        </div>
        <div class="lead gallery">
          <h2><%= link_to "Gallery", gallery_path %></h2>
          <%# keyboard gallery link and photo %>
          <%# cable gallery link and photo %>
        </div>
        <%# <div class="lead shop">
          <h2><%= link_to "Shop", "/shop" %></h2>
        <%# </div> %> 
        <div class="lead build_service">
          <h2><%= link_to "Build Service", new_build_service_path %></h2>
          <p>Interested in having me build a keyboard for you? I would love to solder and assemble your new keyboard.
            Fill out my form for additional information!</p>
        </div>

    </main>

    </div>

    </body>

    </html>

app/views/shop/checkout.html.erb
<h1>Checkout<h1>

app/views/shop/index.html.erb
<h1>Shop#index</h1>
<p>Find me in app/views/shop/index.html.erb</p>