config/routes.rb
Rails.application.routes.draw do
  resources :blog_posts
  devise_for :users
  resources :build_services
  resources :cables
  resources :keyboards
  root 'home#index'
  get '/blog', to: 'blog#index'
  get '/shop/checkout', to: 'shop#checkout'
  get '/gallery', to: 'gallery#index'
  get '/gallery/keyboards', to: 'gallery#keyboards'
  get '/gallery/cables', to: 'gallery#cables'
  
  # This line mounts Solidus's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Solidus relies on it being the default of "spree"
  # mount Spree::Core::Engine, at: '/shop'

  # mount SolidusPaypalCommercePlatform::Engine, at: '/solidus_paypal_commerce_platform'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get ':controller(/:action(/:id))'
end

app/models/build_service.rb
class BuildService < ApplicationRecord
end

app/controllers/build_services_controller.rb
class BuildServicesController < ApplicationController
  before_action :set_build_service, only: %i[ show edit update destroy ]

  # GET /build_services or /build_services.json
  def index
    @build_services = BuildService.all
  end

  # GET /build_services/1 or /build_services/1.json
  def show
  end

  # GET /build_services/new
  def new
    @build_service = BuildService.new
  end

  # GET /build_services/1/edit
  def edit
  end

  # POST /build_services or /build_services.json
  def create
    @build_service = BuildService.new(build_service_params)

    respond_to do |format|
      if @build_service.save
        format.html { redirect_to @build_service, notice: "Build service was successfully created." }
        format.json { render :show, status: :created, location: @build_service }
        # send email to me with build service details
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @build_service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /build_services/1 or /build_services/1.json
  def update
    respond_to do |format|
      if @build_service.update(build_service_params)
        format.html { redirect_to @build_service, notice: "Build service was successfully updated." }
        format.json { render :show, status: :ok, location: @build_service }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @build_service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /build_services/1 or /build_services/1.json
  def destroy
    @build_service.destroy
    respond_to do |format|
      format.html { redirect_to build_services_url, notice: "Build service was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_build_service
      @build_service = BuildService.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def build_service_params
      params.require(:build_service).permit(:name, :email, :keyboard, :switches, :lube_service, :build_timeline, :address, :paypal)
    end
end

app/helpers/build_service_helper.rb
module BuildServiceHelper
end

app/helpers/build_services_helper.rb
module BuildServicesHelper
end

app/views/build_services/_form.html.erb
<p>Interested in having me build your keyboard live on Twitch? Fill out this form and we can talk about what you're looking for. At this time, I do not source parts so please note that all parts will need to be shipped to me prior to the build.</p>
<%= form_with(model: build_service) do |form| %>
  <% if build_service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(build_service.errors.count, "error") %> prohibited this build_service from being saved:</h2>

      <ul>
        <% build_service.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :keyboard %>
    <%= form.text_field :keyboard %>
  </div>

  <div class="field">
    <%= form.label :switches %>
    <%= form.text_field :switches %>
  </div>

  <div class="field">
    <%= form.label :lube_service? %>
    <%= form.check_box :lube_service %>
  </div>

  <div class="field">
    <%= form.label :build_timeline %>
    <%= form.datetime_select :build_timeline %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_area :address %>
  </div>

  <div class="field">
    <%= form.label :paypal %>
    <%= form.text_field :paypal %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/build_services/edit.html.erb
<h1>Editing Build Service</h1>

<%= render 'form', build_service: @build_service %>

<%= link_to 'Show', @build_service %> |
<%= link_to 'Back', build_services_path %>

app/views/build_services/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Build Services</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Keyboard</th>
      <th>Switches</th>
      <th>Lube service</th>
      <th>Build timeline</th>
      <th>Address</th>
      <th>Paypal</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @build_services.each do |build_service| %>
      <tr>
        <td><%= build_service.name %></td>
        <td><%= build_service.email %></td>
        <td><%= build_service.keyboard %></td>
        <td><%= build_service.switches %></td>
        <td><%= build_service.lube_service %></td>
        <td><%= build_service.build_timeline %></td>
        <td><%= build_service.address %></td>
        <td><%= build_service.paypal %></td>
        <td><%= link_to 'Show', build_service %></td>
        <td><%= link_to 'Edit', edit_build_service_path(build_service) %></td>
        <td><%= link_to 'Destroy', build_service, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Build Service', new_build_service_path %>

app/views/build_services/new.html.erb
<h1>New Build Service</h1>

<%= render 'form', build_service: @build_service %>

<%= link_to 'Back', "/" %>

app/views/build_services/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @build_service.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @build_service.email %>
</p>

<p>
  <strong>Keyboard:</strong>
  <%= @build_service.keyboard %>
</p>

<p>
  <strong>Switches:</strong>
  <%= @build_service.switches %>
</p>

<p>
  <strong>Lube service:</strong>
  <%= @build_service.lube_service %>
</p>

<p>
  <strong>Build timeline:</strong>
  <%= @build_service.build_timeline %>
</p>

<p>
  <strong>Address:</strong>
  <%= @build_service.address %>
</p>

<p>
  <strong>Paypal:</strong>
  <%= @build_service.paypal %>
</p>

<%= link_to 'Edit', edit_build_service_path(@build_service) %>
<%# <%= link_to 'Back', build_services_path %> 